package org.plan.research.minimization.plugin.psi.stub

enum class StubDescriptor {
    BLOCK_EXPRESSION, CLASS, CLASS_BODY, FUNCTION, OBJECT, PARAMETER, PARAMETER_LIST, PRIMARY_CONSTRUCTOR, PROPERTY, SECONDARY_CONSTRUCTOR, TYPE_ALIAS
}
