name: "Project Minimization: build and run tests"

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build-and-run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.5

      - name: Build Plugin with Gradle
        run: ./gradlew buildPlugin

      - name: Run Tests
        run: ./gradlew test
      - name: Store reports
        uses: dorny/test-reporter@v1
        if: failure() || success()
        with:
          name: JUnit Tests
          path: "**/build/test-results/test/*.xml"
          reporter: java-junit

